#!/usr/bin/env bash

curl -LO http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz

tar -xaf android-sdk_r24.4.1-linux.tgz -C .
export ANDROID_HOME=$PWD/android-sdk-linux
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"

echo y | android update sdk --no-ui --all --filter "tools"
echo y | android update sdk --no-ui --all --filter "platform-tools"
echo y | android update sdk --no-ui --all --filter "build-tools-23.0.3"
echo y | android update sdk --no-ui --all --filter "android-23"
echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
echo y | android update sdk --no-ui --all --filter "extra-android-support"
echo y | android update sdk --no-ui --all --filter "extra-google-m2repository"
echo y | android update sdk --no-ui --all --filter "extra-google-google_play_services"

echo y | android update sdk --no-ui --all --filter "sys-img-armeabi-v7a-android-23"
echo y | android update sdk --no-ui --all --filter "sys-img-x86-android-23"

echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
emulator -avd test -no-skin -no-audio -no-window &
adb wait-for-device
adb shell input keyevent 82 &

./gradlew clean build connectedCheck
